import { Component } from '@angular/core';

@Component({
  selector: 'app-homepage',
  templateUrl: './homepage.component.html',
  styleUrls: ['./homepage.component.scss']
})
export class HomepageComponent {

  recentReleases: any[] = [{ name: "Models", selected: true }, { name: "Data sets", selected: false }, { name: "Endpoints", selected: false },
  { name: "Pipelines", selected: false }]

  itemList: any[] = [
    { "category": "AICloud", "title": "Codegen", "status": "Deployed", "lastUpdatedDate": "19 Apr 2023 14:04:28", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero quod neque exercitationem enim animi assumenda alias! Earum sapiente quaerat cum error at nostrum vero ex, optio sed ipsum itaque dicta voluptatibus quia ab possimus ullam vitae, ea natus sequi, mollitia hic eum. Consequatur, quibusdam ut? Quidem provident ad in excepturi, saepe quo laborum laboriosam quia, voluptatum ducimus atque! Fugiat voluptates delectus quia quae, laborum at consequatur praesentium autem dolor corporis est culpa eos ut sint ratione provident eveniet hic aliquam doloribus molestias? Veniam, enim reprehenderit corrupti rerum repellendus a placeat cumque? Omnis natus voluptatem quaerat vero error? Asperiores, non quaerat.", "lastUpdatedByThumbnail": "JG", "lastUpdatedBy": "Jane Goodall" },
    { "category": "AICloud", "title": "Stable diffusion", "status": "Deployed", "lastUpdatedDate": "19 Apr 2023 14:04:28", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero quod neque exercitationem enim animi assumenda alias! Earum sapiente quaerat cum error at nostrum vero ex, optio sed ipsum itaque dicta voluptatibus quia ab possimus ullam vitae, ea natus sequi, mollitia hic eum. Consequatur, quibusdam ut? Quidem provident ad in excepturi, saepe quo laborum laboriosam quia, voluptatum ducimus atque! Fugiat voluptates delectus quia quae, laborum at consequatur praesentium autem dolor corporis est culpa eos ut sint ratione provident eveniet hic aliquam doloribus molestias? Veniam, enim reprehenderit corrupti rerum repellendus a placeat cumque? Omnis natus voluptatem quaerat vero error? Asperiores, non quaerat.", "lastUpdatedByThumbnail": "JG", "lastUpdatedBy": "Jane Goodall" },
    { "category": "AICloud", "title": "Bloom7b1", "status": "Deployed", "lastUpdatedDate": "19 Apr 2023 14:04:28", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero quod neque exercitationem enim animi assumenda alias! Earum sapiente quaerat cum error at nostrum vero ex, optio sed ipsum itaque dicta voluptatibus quia ab possimus ullam vitae, ea natus sequi, mollitia hic eum. Consequatur, quibusdam ut? Quidem provident ad in excepturi, saepe quo laborum laboriosam quia, voluptatum ducimus atque! Fugiat voluptates delectus quia quae, laborum at consequatur praesentium autem dolor corporis est culpa eos ut sint ratione provident eveniet hic aliquam doloribus molestias? Veniam, enim reprehenderit corrupti rerum repellendus a placeat cumque? Omnis natus voluptatem quaerat vero error? Asperiores, non quaerat.", "lastUpdatedByThumbnail": "JG", "lastUpdatedBy": "Jane Goodall" },
    { "category": "AICloud", "title": "Flant5-xl", "status": "Deployed", "lastUpdatedDate": "19 Apr 2023 14:04:28", "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero quod neque exercitationem enim animi assumenda alias! Earum sapiente quaerat cum error at nostrum vero ex, optio sed ipsum itaque dicta voluptatibus quia ab possimus ullam vitae, ea natus sequi, mollitia hic eum. Consequatur, quibusdam ut? Quidem provident ad in excepturi, saepe quo laborum laboriosam quia, voluptatum ducimus atque! Fugiat voluptates delectus quia quae, laborum at consequatur praesentium autem dolor corporis est culpa eos ut sint ratione provident eveniet hic aliquam doloribus molestias? Veniam, enim reprehenderit corrupti rerum repellendus a placeat cumque? Omnis natus voluptatem quaerat vero error? Asperiores, non quaerat.", "lastUpdatedByThumbnail": "JG", "lastUpdatedBy": "Jane Goodall" },
  ]

}
