<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.infosys.icets.ai</groupId>
		<artifactId>aip</artifactId>
		<version>3.3-SNAPSHOT</version>
	</parent>
	<groupId>com.infosys</groupId>
	<artifactId>common-lib-rest</artifactId>
	<packaging>jar</packaging>
	<name>common-lib-rest</name>
	<properties>
		<main.basedir>${project.parent.basedir}</main.basedir>
	</properties>
	<repositories>
		<repository>
			<id>maven-remote</id>
			<url>https://infyartifactory.jfrog.io/artifactory/icets-maven-virtual</url>
		</repository>
		<repository>
			<id>central</id>
			<url>https://infyartifactory.jfrog.io/artifactory/icets-maven-virtual</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
			<id>central</id>
			<name>jenkins_plugin</name>
			<url>https://infyartifactory.jfrog.io/artifactory/jenkins_plugin</url>
		</pluginRepository>
		<pluginRepository>
			<snapshots />
			<id>snapshots</id>
			<name>jenkins_plugin</name>
			<url>https://infyartifactory.jfrog.io/artifactory/jenkins_plugin</url>
		</pluginRepository>
	</pluginRepositories>
	<distributionManagement>
		<repository>
			<id>central</id>
			<name>infyartifactory.jfrog.io-releases</name>
			<url>https://infyartifactory.jfrog.io/artifactory/icets-ai_maven
			</url>
		</repository>
		<snapshotRepository>
			<id>snapshots</id>
			<name>infyartifactory.jfrog.io-snapshots</name>
			<url>https://infyartifactory.jfrog.io/artifactory/icets-ai_maven
			</url>
		</snapshotRepository>
	</distributionManagement>
	<dependencies>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>2.0.1.Final</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>

		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>

		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>

		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.modelmapper</groupId>
			<artifactId>modelmapper</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.14</version>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-collections4</artifactId>
		</dependency>
		
		<dependency>
			<groupId>com.infosys.icets.ai</groupId>
			<artifactId>comm-lib-util</artifactId>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.ai</groupId>
			<artifactId>comm-lib-licval</artifactId>
		</dependency>
		<!-- Test dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.openpojo</groupId>
			<artifactId>openpojo</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>


</project>
