<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.infosys</groupId>
	<artifactId>icip-assembly</artifactId>
	<version>3.2-SNAPSHOT</version>
	<packaging>pom</packaging>
	<url>http://maven.apache.org</url> 
	<parent>
		<groupId>com.infosys.icets.ai</groupId>
		<artifactId>icets_ai</artifactId>
		<version>3.2-SNAPSHOT</version>
	</parent>
	<dependencies>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-beans</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-aop</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-expression</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-commons</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
		</dependency>
		<dependency>
			<groupId>org.liquibase</groupId>
			<artifactId>liquibase-core</artifactId>
		</dependency>
		<dependency>
                        <groupId>com.sun.xml.bind</groupId>
                        <artifactId>jaxb-impl</artifactId>
                        <version>2.3.3</version>
                </dependency>
                <dependency>
                        <groupId>jakarta.servlet</groupId>
                        <artifactId>jakarta.servlet-api</artifactId>
                        <version>6.0.0</version>
                        <scope>provided</scope>
               </dependency>
               <dependency>
                        <groupId>com.microsoft.graph</groupId>
                         <artifactId>microsoft-graph</artifactId>
                         <version>5.9.0</version>
               </dependency>
	       <dependency>
                          <groupId>com.microsoft.graph</groupId>
                          <artifactId>microsoft-graph-core</artifactId>
                          <version>2.0.10</version>
              </dependency>
		<!-- Core modules -->
		<dependency>
			<groupId>com.infosys</groupId>
			<artifactId>common-app</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.ai</groupId>
			<artifactId>comm-lib-util</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		 <dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-azure-openai</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-aws-bedrock</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-vertexai</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
                        <groupId>com.infosys.icets.ai</groupId>
                        <artifactId>comm-lib-secrets</artifactId>
                        <version>${project.parent.version}</version>
                </dependency>
		<dependency>
                        <groupId>com.infosys.icets.ai</groupId>
                        <artifactId>comm-secrets-app</artifactId>
                        <version>${project.parent.version}</version>
                </dependency>
	<!--	<dependency>
                        <groupId>com.infosys.icets.ai</groupId>
                        <artifactId>comm-secrets-vault</artifactId>
                        <version>${project.parent.version}</version>
                </dependency> -->
		<dependency>
			<groupId>com.infosys.icets.ai</groupId>
			<artifactId>comm-lib-licval</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys</groupId>
			<artifactId>iamp-lib-usm</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
                         <groupId>com.infosys.icets.icip</groupId>
                         <artifactId>icip-lib-ivm</artifactId>
                         <version>${project.parent.version}</version>
                </dependency>
	<!--	<dependency>
                      <groupId>com.infosys</groupId>
			<artifactId>iamp-lib-dbs</artifactId>
			<version>${project.parent.version}</version>
		</dependency> -->
		<dependency>
			<groupId>com.infosys</groupId>
			<artifactId>svy-lib-mat</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-fsvr</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-adp</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-gitconf</artifactId>
			<version>3.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-search</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-iai</artifactId>
			<version>${project.parent.version}</version>
			<exclusions>
			<exclusion>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			</exclusion>
			</exclusions>
		</dependency>
       <!--         <dependency>
			<groupId>com.infosys</groupId>
			<artifactId>iamp-lib-ied</artifactId>
			<version>${project.parent.version}</version>
		</dependency>  -->
                <dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-exp</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-minio</artifactId>
			<version>3.0-SNAPSHOT</version>
		</dependency>	
	<!--	<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-dgbrain</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-dgbrain</artifactId>
			<version>${project.parent.version}</version>
		</dependency> -->
		<dependency>
                       <groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-features</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
                         <artifactId>icip-adp-feast</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
                         <artifactId>icip-adp-mlflow</artifactId>
			<version>3.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-dynamic</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-aicloud</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
                        <artifactId>icip-adp-servicenow</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
                         <artifactId>icip-adp-mysql</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-file</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-h2</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-remote</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-rest</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-s3</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-jobs</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-evt</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-mod</artifactId>
			<version>${project.parent.version}</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-mlops</artifactId>
			<version>${project.parent.version}</version>
		</dependency>	
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-postgresql</artifactId>
			<version>${project.parent.version}</version>
		</dependency>	
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-aws-emr</artifactId>
			<version>3.0-SNAPSHOT</version>
                </dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-aws-sagemaker</artifactId>
			<version>3.1-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-gcp-vertex</artifactId>
			<version>3.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip.plugins</groupId>
			<artifactId>icip-adp-azure</artifactId>
			<version>3.2-SNAPSHOT</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-resources-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-resources</id>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/icip-app/conf</outputDirectory>
							<resources>
								<resource>
									<directory>src/main/resources</directory>
									<filtering>true</filtering>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-app</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
							<excludeGroupIds>*</excludeGroupIds>
							<includeArtifactIds>common-app</includeArtifactIds>
							<outputDirectory>${project.build.directory}/icip-app/</outputDirectory>
						</configuration>
					</execution>
					<execution>
						<id>unpack</id>
						<phase>package</phase>
						<goals>
							<goal>unpack</goal>
						</goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>com.infosys</groupId>
									<artifactId>common-app</artifactId>
									<version>${project.parent.version}</version>
									<type>jar</type>
									<overWrite>false</overWrite>
									<outputDirectory>${project.build.directory}/temp</outputDirectory>
									<destFileName>optional-new-name.jar</destFileName>
									<includes>*.xml,*.properties,*.yml,*.config</includes>
									<excludes>**/*test.class,**/*.java,application-dev.yml</excludes>
								</artifactItem>
							</artifactItems>
							<outputDirectory>${project.build.directory}/icip-app/conf</outputDirectory>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>true</overWriteSnapshots>
						</configuration>
					</execution>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
							<excludeArtifactIds>lombok</excludeArtifactIds>
							<excludeGroupIds>com.infosys.icets.iamp,com.infosys,com.infosys.icets.icip.plugins,com.infosys.icets.ai</excludeGroupIds>
							<outputDirectory>${project.build.directory}/icip-app/lib</outputDirectory>
						</configuration>
					</execution>
					<execution>
						<id>copy-modules</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
							<excludeScope />
							<excludeGroupIds>com.infosys.icets.icip.plugins</excludeGroupIds>
							<excludeArtifactIds>common-app</excludeArtifactIds>
							<includeGroupIds>com.infosys.icets.icip,com.infosys,com.infosys.icets.ai</includeGroupIds>
							<outputDirectory>${project.build.directory}/icip-app/modules</outputDirectory>
						</configuration>
					</execution>
					<execution>
						<id>copy-plugins</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<overWriteReleases>false</overWriteReleases>
							<overWriteSnapshots>false</overWriteSnapshots>
							<overWriteIfNewer>true</overWriteIfNewer>
							<excludeScope />
							<includeGroupIds>com.infosys.icets.icip.plugins</includeGroupIds>
							<outputDirectory>${project.build.directory}/icip-app/plugins</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<finalName>icip-app-${project.version}</finalName>
					<appendAssemblyId>false</appendAssemblyId>
					<descriptors>
						<descriptor>assembly.xml</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>com.mycila</groupId>
				<artifactId>license-maven-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<skip>true</skip>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
