apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: builder-service-ingress
  namespace: essedum
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/websocket-services: "builder-service"
    nginx.ingress.kubernetes.io/upstream-keepalive-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - essedum.local
    secretName: essedum-tls
  rules:
  - host: essedum.local
    http:
      paths:
      - path: /apps/builder-service(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: builder-service
            port:
              number: 80
