apiVersion: apps/v1
kind: Deployment
metadata:
  name: essedum-backend-data
  namespace: aipns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: essedum-backend-data
  template:
    metadata:
      labels:
        app: essedum-backend-data
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: essedum-backend-data
        image: acrreq0762935.azurecr.io/essedum-data-service:v15
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args: ["java ${JAVA_OPTS:--Xms128m -Xmx256m} -Dspring.config.location=/app/conf/ -DLOG_PATH=/app/log -jar $(ls /app/data-service*.jar | head -1)"]
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "mysql,oauth2,dbconstants"
        - name: OAUTH2_ISSUER_URI
          value: "https://aiplatform.az.ad.idemo-ppc.com/realms/ESSEDUM"
        - name: OAUTH2_JWK_URI
          value: "http://keycloak:8180/realms/ESSEDUM/protocol/openid-connect/certs"
        - name: MYSQL_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: essedum-db-secret
              key: MYSQL_DATASOURCE_URL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: essedum-db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: essedum-db-secret
              key: MYSQL_PASSWORD
        - name: ENCRYPTION_KEY
          value: "leap$123##"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: essedum-backend-data-service
  namespace: aipns
spec:
  selector:
    app: essedum-backend-data
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP
