apiVersion: apps/v1
kind: Deployment
metadata:
  name: essedum-backend-data
  namespace: aipns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: essedum-backend-data
  template:
    metadata:
      labels:
        app: essedum-backend-data
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: essedum-1
      hostAliases:
      - ip: "192.168.28.41"
        hostnames:
        - "keycloak.essedum.local"
      containers:
      - name: essedum-backend-data
        image: ${DOCKER_REGISTRY}/essedum-data-service:${IMAGE_TAG}
        imagePullPolicy: Always
        env:
        - name: MYSQL_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: essedum-db-secret
              key: MYSQL_DATASOURCE_URL
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: essedum-db-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: essedum-db-secret
              key: MYSQL_PASSWORD
        - name: OAUTH2_JWK_URI
          value: "http://keycloak.essedum.svc.cluster.local:8080/realms/ESSEDUM/protocol/openid-connect/certs"
        - name: OAUTH2_ISSUER_URI
          value: "https://keycloak.essedum.local:30443/realms/ESSEDUM"
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: essedum-backend-data-service
  namespace: aipns
spec:
  selector:
    app: essedum-backend-data
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP
