apiVersion: apps/v1
kind: Deployment
metadata:
  name: essedum-ui
  namespace: essedum
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: essedum-ui
  template:
    metadata:
      labels:
        app: essedum-ui
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: essedum-ui
        image: ${REGISTRY}/essedum/frontend:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        - containerPort: 8084
