apiVersion: apps/v1
kind: Deployment
metadata:
  name: essedum-frontend-shell
  namespace: aipns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: essedum-frontend-shell
  template:
    metadata:
      labels:
        app: essedum-frontend-shell
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/hostname: essedum-1
      containers:
      - name: essedum-frontend-shell
        image: ${DOCKER_REGISTRY}/essedum-frontend-shell:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        volumeMounts:
        - name: auth-config-vol
          mountPath: /app/ui/shell/configs/auth-config.json
          subPath: auth-config.json
      volumes:
      - name: auth-config-vol
        configMap:
          name: essedum-auth-config
---
apiVersion: v1
kind: Service
metadata:
  name: essedum-frontend-shell-service
  namespace: aipns
spec:
  selector:
    app: essedum-frontend-shell
  ports:
  - protocol: TCP
    port: 8084
    targetPort: 8084
  type: ClusterIP
