apiVersion: apps/v1
kind: Deployment
metadata:
  name: essedum-frontend-agent
  namespace: aipns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: essedum-frontend-agent
  template:
    metadata:
      labels:
        app: essedum-frontend-agent
    spec:
      containers:
      - name: essedum-frontend-agent
        image: ${DOCKER_REGISTRY}/essedum-frontend-agent:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command: ["/bin/sh", "-c"]
        args:
        - "find /app/ui -type f -name '*.js' -exec sed -i \"s|__FE_MINIO_ENDPOINT__|${FE_MINIO_ENDPOINT}|g; s|__FE_MINIO_BUCKET__|${FE_MINIO_BUCKET}|g; s|__FE_CONTAINER_REGISTRY_PREFIX__|${FE_CONTAINER_REGISTRY_PREFIX}|g; s|__FE_CONTAINER_REGISTRY_VERSION__|${FE_CONTAINER_REGISTRY_VERSION}|g\" {} + && nginx -g 'daemon off;'"
        env:
        - name: FE_MINIO_ENDPOINT
          value: "http://minio-service:9000"
        - name: FE_MINIO_BUCKET
          value: "aiptest"
        - name: FE_CONTAINER_REGISTRY_PREFIX
          value: "${DOCKER_REGISTRY}/"
        - name: FE_CONTAINER_REGISTRY_VERSION
          value: "${IMAGE_TAG}"
---
apiVersion: v1
kind: Service
metadata:
  name: essedum-frontend-agent-service
  namespace: aipns
spec:
  selector:
    app: essedum-frontend-agent
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
