apiVersion: apps/v1
kind: Deployment
metadata:
  name: essedum-backend
  namespace: essedum
spec:
  replicas: 1 # Number of replicas
  selector:
    matchLabels:
      app: essedum-backend
  template:
    metadata:
      labels:
        app: essedum-backend
    spec:
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        registry: "local"
      containers:
      - name: essedum-backend
        image: ${REGISTRY}/essedum/leap-app-backend:${IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        env:
        - name: security.issuer-uri
          value: "https://essedum.local/realms/ESSEDUM"
        - name: security.jwk-set-uri
          value: "http://keycloak.essedum.svc.cluster.local:8080/realms/ESSEDUM/protocol/openid-connect/certs"
        - name: security.clientId
          value: "essedum-45"
        - name: security.scope
          value: "openid profile email"
        - name: MYSQL_DATASOURCE_URL
          value: "mysql.essedum.svc.cluster.local"
        - name: MYSQL_DATASOURCE_USER
          value: "root"
        - name: MYSQL_DATASOURCE_PASSWORD
          value: "password"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: essedum-backend-service
  namespace: essedum
spec:
  selector:
    app: essedum-backend # Matches the label in the Deployment
  ports:
  - protocol: TCP
    port: 8080          # External port to expose
    targetPort: 8082  # Port where the application is running inside the pod
  type: LoadBalancer
