
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: aipns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.3
          args:
            - "start-dev"
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_HTTP_PORT
              value: "8180"
            - name: KC_HTTPS_ENABLED
              value: "false"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME
              value: "login.lfn.essedum.anuket.iol.unh.edu"
            - name: KC_DB
              value: "mysql"
            - name: KC_DB_URL
              value: "jdbc:mysql://mysql.aipns.svc.cluster.local:3306/keycloak"
            - name: KC_DB_USERNAME
              value: "root"
            - name: KC_DB_PASSWORD
              value: "password"
          ports:
            - containerPort: 8180
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8180
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8180
            initialDelaySeconds: 60
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: aipns
spec:
  type: LoadBalancer
  loadBalancerIP: 10.200.111.204
  selector:
    app: keycloak
  ports:
    - name: http
      protocol: TCP
      port: 8180
      targetPort: 8180

