apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: essedum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      nodeSelector:
        registry: "local"
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.3
          args:
            - "start-dev"
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: admin-user
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: admin-password
            - name: KC_HTTP_PORT
              value: "8080"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTPS_ENABLED
              value: "false"
            - name: KC_HOSTNAME
              value: "essedum.local"
            - name: KC_HOSTNAME_ADMIN
              value: "keycloak.essedum.local"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_DB
              value: mysql
            - name: KC_DB_URL
              value: "jdbc:mysql://mysql:3306/keycloak"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: db-username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: db-password
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: essedum
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
