apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: aipns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.3
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1536Mi"
          args:
            - "start-dev"
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: password
            - name: KC_HTTP_PORT
              value: "8180"
            - name: KC_HTTPS_PORT
              value: "8443"
            - name: KC_PROXY
              value: "edge"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTPS_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: "https://${INGRESS_HOST}"
            - name: KC_HOSTNAME_ADMIN
              value: "https://${KEYCLOAK_INGRESS_HOST}"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: "/etc/keycloak/certs/tls.crt"
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: "/etc/keycloak/certs/tls.key"
            - name: KC_DB
              value: mysql
            - name: KC_DB_URL
              value: "jdbc:mysql://mysql.aipns.svc.cluster.local:3306/keycloak"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: essedum-db-secret
                  key: MYSQL_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: essedum-db-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8180
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: 8180
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 24
          readinessProbe:
            tcpSocket:
              port: 8180
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8180
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6

          volumeMounts:
            - name: tls-cert
              mountPath: /etc/keycloak/certs
              readOnly: true
      volumes:
        - name: tls-cert
          secret:
            secretName: essedum-secret


---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: aipns
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: keycloak
  ports:
    - name: keycloak-https
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: keycloak-http
      protocol: TCP
      port: 8180
      targetPort: 8180
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
  type: LoadBalancer
