apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langflow-ingress
  namespace: aipns
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - langflow.lfn.essedum.anuket.iol.unh.edu
      secretName: langflow-tls
  rules:
    - host: langflow.lfn.essedum.anuket.iol.unh.edu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: langflow
                port:
                  number: 7860
