apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3JyZXEwNzYyOTM1LmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhY3JSRVEwNzYyOTM1IiwicGFzc3dvcmQiOiI5Z1Q3WStLbmN1QmhQNU93aUdsdC9TYlZqQnRRRC82Q2RmdzRjSnpMQTMrQUNSRHBNNXdIIiwiYXV0aCI6IllXTnlVa1ZSTURjMk1qa3pOVG81WjFRM1dTdExibU4xUW1oUU5VOTNhVWRzZEM5VFlsWnFRblJSUkM4MlEyUm1kelJqU25wTVFUTXJRVU5TUkhCTk5YZEkifX19
kind: Secret
metadata:
  name: regcred
  namespace: aipns
type: kubernetes.io/dockerconfigjson
