apiVersion: v1
data:
  AWS_ACCESS_KEY_ID: aU5GZVlpdUtFSU40QXpVSjNWUm0=
  AWS_REGION: dXMtZWFzdC0x
  AWS_SECRET_ACCESS_KEY: dTdrcVNGQW9CMjc0cXpxZ0JCcXdiOFJzVjVYcElCczBVZHk5ZjA1Nw==
  MINIO_ENDPOINT: aHR0cDovLzEwMC43OC40OS4yMDo5MDAw
kind: Secret
metadata:
  name: s3-credentials
  namespace: aipns
type: Opaque
