
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vibe-code-builder-service
  namespace: aipns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vibe-code-builder
  template:
    metadata:
      labels:
        app: vibe-code-builder
    spec:
      serviceAccountName: builder-sa  # Grants permission per RBAC
      imagePullSecrets:
        - name: regcred
      containers:
        - name: vibe-code-builder
          image: acrreq0762935.azurecr.io/vibe-code-builder-service:v15
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "2"
              memory: "2Gi"
          envFrom:
            - secretRef:
                name: vibe-code-builder-secret
          volumeMounts:
            - name: dockerfile-template
              mountPath: /opt/fallback
      volumes:
        - name: dockerfile-template
          configMap:
            name: vibe-code-builder-dockerfile-template
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: vibe-code-builder-service
  namespace: aipns
spec:
  selector:
    app: vibe-code-builder
  ports:
    - port: 80
      targetPort: 5000
  type: LoadBalancer
  sessionAffinity: ClientIP
