stages:
- name: Build
  steps:
  - runScriptConfig:
      image: infyartifactory.ad.infosys.com/docker-local/leap/builder-java:139-1
      shellScript: |-
        export MAVEN_CLI_OPTS="-s .m2/settings.xml --batch-mode"
        mvn clean $MAVEN_CLI_OPTS deploy -DskipTests=true
    envFrom:
    - sourceName: cred
      sourceKey: MAVEN_REPO_USER
    - sourceName: cred
      sourceKey: MAVEN_REPO_PASS
    - sourceName: cred
      sourceKey: MAVEN_LOCAL_REPO
branch:
  include:
  - master
notification: {}
