<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.infosys.icets.ai</groupId>
		<artifactId>aip</artifactId>
		<version>3.3-SNAPSHOT</version>
	</parent>
	<groupId>com.infosys.icets.icip.plugins</groupId>
	<artifactId>icip-adp-aicloud</artifactId>
	<name>icip-adp-aicloud</name>
	<distributionManagement>
		<repository>
			<id>central</id>
			<name>infyartifactory.ad.infosys.com-releases</name>
			<url>https://infyartifactory.jfrog.io/artifactory/icets-ai_maven</url>
		</repository>
		<snapshotRepository>
			<id>snapshots</id>
			<name>infyartifactory.ad.infosys.com-snapshots</name>
			<url>https://infyartifactory.jfrog.io/artifactory/icets-ai_maven</url>
		</snapshotRepository>
	</distributionManagement>
	<repositories>
		<repository>
			<id>central</id>
			<name>infyartifactory.ad.infosys.com-releases</name>
			<url>https://infyartifactory.jfrog.io/artifactory/icets-ai_maven</url>
		</repository>
		<repository>
			<id>snapshots</id>
			<name>infyartifactory.ad.infosys.com-snapshots</name>
			<url>https://infyartifactory.jfrog.io/artifactory/icets-ai_maven</url>
		</repository>
		<repository>
			<id>maven-remote</id>
			<name>maven-remote</name>
			<url>https://infyartifactory.jfrog.io/artifactory/maven-remote</url>
		</repository>
		<repository>
			<id>jcenter</id>
			<name>jcenter-cache</name>
			<url>https://infyartifactory.jfrog.io/artifactory/jcenter</url>
		</repository>
	</repositories>
	<pluginRepositories>
		<pluginRepository>
			<id>libs-release</id>
			<name>libs-release</name>
			<url>hhttps://infyartifactory.jfrog.io/artifactory/libs-release</url>
		</pluginRepository>
		<pluginRepository>
			<id>maven-remote</id>
			<name>maven-remote</name>
			<url>https://infyartifactory.jfrog.io/artifactory/maven-remote</url>
		</pluginRepository>
		<pluginRepository>
			<id>jcenter</id>
			<name>jcenter</name>
			<url>https://infyartifactory.jfrog.io/artifactory/jcenter</url>
		</pluginRepository>
	</pluginRepositories>
	<dependencies>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<scope>provided</scope>
		</dependency>
        <dependency>
         <groupId>org.elasticsearch.client</groupId>
         <artifactId>elasticsearch-rest-high-level-client</artifactId>
         <version>7.17.28</version>
        </dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-adp</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.icip</groupId>
			<artifactId>icip-lib-mod</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.ai</groupId>
			<artifactId>comm-lib-util</artifactId>
		</dependency>
		<dependency>
			<groupId>com.infosys.icets.ai</groupId>
			<artifactId>comm-lib-secrets</artifactId>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<configuration>
					<outputDirectory>${project.build.directory}/plugin</outputDirectory>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<configuration>
					<finalName>aicloud-plugin-${project.version}</finalName>
					<appendAssemblyId>false</appendAssemblyId>
					<descriptors>
						<descriptor>assembly.xml</descriptor>
					</descriptors>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
