import { Injectable } from '@angular/core';
import { DataPipelineCfg, TrainingJobCfg } from './pipeline-options.constants';

// Pure string-builder. No I/O, no DI dependencies — fully testable.
// Ported from the React reference's generateCode() in DataPipelineEditorPage.tsx
// and TrainingJobEditorPage.tsx, adapted to Essedum's container/executor API.
@Injectable({ providedIn: 'root' })
export class CodeTemplateService {

  generateDataPipelineCode(cfg: DataPipelineCfg): string {
    const bodyByType: Record<string, () => string> = {
      'feature-engineering': () => this.featureEngineeringBody(cfg),
      'data-cleaning':       () => this.dataCleaningBody(cfg),
      'etl':                 () => this.etlBody(cfg),
      'rag-ingestion':       () => this.ragIngestionBody(cfg),
      'slm-sft':             () => this.slmSftBody(cfg),
      'slm-cot':             () => this.slmCotBody(cfg),
      'slm-dpo':             () => this.slmDpoBody(cfg),
      'slm-pretrain':        () => this.slmPretrainBody(cfg),
    };
    const body = (bodyByType[cfg.pipelineType] ?? bodyByType['feature-engineering'])();
    const safeName = (cfg.name || 'pipeline').replace(/-/g, '_');
    return `"""
Auto-generated by Essedum Platform
Pipeline : ${cfg.name}
Type     : ${cfg.pipelineType}
Source   : ${cfg.connection}
Output   : ${cfg.outputContainer}
Executor : ${cfg.executor}
"""

import os
import pandas as pd
import numpy as np
from essedum.data import DataContainer
from essedum.pipeline import executor

# ── 1. Load data ──────────────────────────────────────────────────────────
dc        = DataContainer.from_connection("${cfg.connection}")
output_dc = DataContainer.from_dataset("${cfg.outputContainer}")

df = dc.query("""
    SELECT *
    FROM your_table
    -- WHERE condition = TRUE
""")
print(f"Loaded {len(df):,} rows × {df.shape[1]} columns")
${body}

# ── Final: Save ───────────────────────────────────────────────────────────
output_dc.write_table(df, "prepared.${safeName}", mode="overwrite")
executor.log_metrics({"rows_output": len(df), "columns": df.shape[1]})
print(f"✓ Saved {len(df):,} rows → '${cfg.outputContainer}'")
`;
  }

  generateTrainingCode(cfg: TrainingJobCfg): string {
    if (cfg.jobType === 'slm-finetune')  return this.slmFinetuneTraining(cfg);
    if (cfg.jobType === 'reasoning')     return this.reasoningTraining(cfg);
    if (cfg.jobType === 'distillation')  return this.distillationTraining(cfg);
    return this.traditionalTraining(cfg);
  }

  // ─── Data-pipeline bodies ─────────────────────────────────────────────

  private featureEngineeringBody(cfg: DataPipelineCfg): string {
    return `
# ── 2. Clean ──────────────────────────────────────────────────────────────
rows_before = len(df)
df = df.drop_duplicates().reset_index(drop=True)

for col in df.select_dtypes("number").columns:
    df[col] = df[col].fillna(df[col].median())
for col in df.select_dtypes("object").columns:
    df[col] = df[col].fillna(df[col].mode()[0])

print(f"Cleaned: {rows_before:,} → {len(df):,} rows")

# ── 3. Feature Engineering ────────────────────────────────────────────────
# TODO: add domain-specific features below
# df["new_feature"] = df["col_a"] / (df["col_b"] + 1e-6)

# ── 4. Encode & Scale ─────────────────────────────────────────────────────
from sklearn.preprocessing import StandardScaler, LabelEncoder

cat_cols = [c for c in df.select_dtypes("object").columns if c != "${cfg.targetCol}"]
for col in cat_cols:
    df[col] = LabelEncoder().fit_transform(df[col].astype(str))

numeric_cols = [c for c in df.select_dtypes("number").columns if c != "${cfg.targetCol}"]
df[numeric_cols] = StandardScaler().fit_transform(df[numeric_cols])`;
  }

  private dataCleaningBody(_cfg: DataPipelineCfg): string {
    return `
# ── 2. Profile ────────────────────────────────────────────────────────────
print("Shape:", df.shape)
print("Missing:", df.isnull().sum()[df.isnull().sum() > 0].to_dict())
rows_before = len(df)

# ── 3. Clean ──────────────────────────────────────────────────────────────
df = df.drop_duplicates().reset_index(drop=True)

for col in df.select_dtypes("number").columns:
    df[col] = df[col].fillna(df[col].median())
for col in df.select_dtypes("object").columns:
    df[col] = df[col].fillna(df[col].mode()[0])

for col in df.select_dtypes("number").columns:
    lo, hi = df[col].quantile(0.01), df[col].quantile(0.99)
    df[col] = df[col].clip(lo, hi)

print(f"Cleaned: {rows_before:,} → {len(df):,} rows")`;
  }

  private etlBody(_cfg: DataPipelineCfg): string {
    return `
# ── 2. Transform ──────────────────────────────────────────────────────────
rows_before = len(df)
df.columns = [c.lower().strip().replace(" ", "_") for c in df.columns]
df = df.drop_duplicates().dropna(subset=["id_col"]).reset_index(drop=True)

# ── 3. Enrich / Join (optional) ───────────────────────────────────────────
# lookup = dc.query("SELECT id, category FROM lookup_table")
# df = df.merge(lookup, on="id_col", how="left")

# ── 4. Validate ───────────────────────────────────────────────────────────
assert df.isnull().sum().sum() == 0, "Nulls remain after cleaning"
assert len(df) > 0, "Output is empty"
print(f"ETL complete: {rows_before:,} → {len(df):,} rows")`;
  }

  private ragIngestionBody(cfg: DataPipelineCfg): string {
    return `
# ── 2. Chunk documents ────────────────────────────────────────────────────
from langchain.text_splitter import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(chunk_size=512, chunk_overlap=64)
chunks = []
for _, row in df.iterrows():
    for i, chunk in enumerate(splitter.split_text(row["content"])):
        chunks.append({"source": row["filename"], "chunk_id": i, "text": chunk})

chunks_df = pd.DataFrame(chunks)
print(f"Created {len(chunks_df):,} chunks from {len(df):,} documents")

# ── 3. Embed ──────────────────────────────────────────────────────────────
from openai import AzureOpenAI
client = AzureOpenAI()
embeddings = []
texts = chunks_df["text"].tolist()
for i in range(0, len(texts), 100):
    resp = client.embeddings.create(model="text-embedding-3-large", input=texts[i:i+100])
    embeddings.extend([e.embedding for e in resp.data])
chunks_df["embedding"] = embeddings

# ── 4. Upsert into Qdrant ─────────────────────────────────────────────────
from qdrant_client import QdrantClient
from qdrant_client.models import PointStruct
qdrant = QdrantClient(url=os.getenv("QDRANT_URL"))
points = [PointStruct(id=i, vector=row["embedding"], payload={"source": row["source"], "text": row["text"]}) for i, row in chunks_df.iterrows()]
qdrant.upsert(collection_name="${cfg.name}", points=points)
print(f"Upserted {len(points):,} vectors into Qdrant")
df = chunks_df`;
  }

  private slmSftBody(cfg: DataPipelineCfg): string {
    const fmt = cfg.outputFormat || 'chatml';
    return `
# ── 2. Build SFT dataset (${fmt}) ─────────────────────────────────────────
# Expects columns: instruction, response (or input/output)
def to_chatml(row):
    return {
        "messages": [
            {"role": "user",      "content": row["instruction"]},
            {"role": "assistant", "content": row["response"]},
        ]
    }

records = [to_chatml(r) for _, r in df.iterrows()]
df = pd.DataFrame(records)
print(f"Built {len(df):,} ${fmt} SFT examples")`;
  }

  private slmCotBody(cfg: DataPipelineCfg): string {
    const teacher = cfg.teacherModel || 'gpt-4o';
    return `
# ── 2. Generate Chain-of-Thought with teacher (${teacher}) ────────────────
from openai import AzureOpenAI
client = AzureOpenAI()

cot_rows = []
for _, row in df.iterrows():
    resp = client.chat.completions.create(
        model="${teacher}",
        messages=[{"role": "system", "content": "Think step by step inside <think>...</think> then give the answer inside <answer>...</answer>."},
                  {"role": "user",   "content": row["question"]}],
        temperature=0.7, max_tokens=1024,
    )
    cot_rows.append({"prompt": row["question"], "solution": resp.choices[0].message.content})

df = pd.DataFrame(cot_rows)
print(f"Distilled {len(df):,} CoT examples from ${teacher}")`;
  }

  private slmDpoBody(_cfg: DataPipelineCfg): string {
    return `
# ── 2. Build DPO preference pairs ─────────────────────────────────────────
# Expects: prompt, chosen, rejected
df = df[["prompt", "chosen", "rejected"]].dropna().reset_index(drop=True)
assert len(df) > 0, "No valid preference pairs found"
print(f"Built {len(df):,} DPO preference pairs")`;
  }

  private slmPretrainBody(_cfg: DataPipelineCfg): string {
    return `
# ── 2. Prepare pre-training corpus ────────────────────────────────────────
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B")

def tokenize(batch):
    return tokenizer(batch["text"], truncation=True, max_length=2048)

from datasets import Dataset
hf_ds = Dataset.from_pandas(df).map(tokenize, batched=True, remove_columns=df.columns.tolist())
print(f"Tokenized {len(hf_ds):,} sequences (max_len=2048)")
df = pd.DataFrame({"input_ids": hf_ds["input_ids"]})`;
  }

  // ─── Training-job templates ───────────────────────────────────────────

  private traditionalTraining(cfg: TrainingJobCfg): string {
    const importsByFw: Record<string, string> = {
      'XGBoost 1.7':      'import xgboost as xgb\nfrom xgboost import XGBClassifier, XGBRegressor',
      'LightGBM 4.1':     'import lightgbm as lgb\nfrom lightgbm import LGBMClassifier, LGBMRegressor',
      'Scikit-learn 1.3': 'from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\nfrom sklearn.linear_model import LogisticRegression',
      'PyTorch 2.1':      'import torch\nimport torch.nn as nn\nfrom torch.utils.data import DataLoader, TensorDataset',
      'TensorFlow 2.14':  'import tensorflow as tf\nfrom tensorflow import keras\nfrom tensorflow.keras import layers',
    };
    const trainBlock = cfg.framework === 'XGBoost 1.7'
      ? `model = XGBClassifier(n_estimators=${cfg.epochs ?? 100}, learning_rate=${cfg.lr ?? 0.1}, max_depth=6, random_state=42)
model.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=50)`
      : cfg.framework === 'LightGBM 4.1'
      ? `model = LGBMClassifier(n_estimators=${cfg.epochs ?? 200}, learning_rate=${cfg.lr ?? 0.05}, num_leaves=31, random_state=42)
model.fit(X_train, y_train, eval_set=[(X_test, y_test)], callbacks=[lgb.early_stopping(30)])`
      : `model = RandomForestClassifier(n_estimators=${cfg.epochs ?? 100}, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)`;
    return `"""
Auto-generated — Traditional ML Training
Job:      ${cfg.name}
Model:    ${cfg.baseModel}
Dataset:  ${cfg.dataset}
Executor: ${cfg.executor}
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, mean_squared_error
${importsByFw[cfg.framework] ?? '# import your framework'}
from essedum.data import DataContainer
from essedum.pipeline import executor, save_artifact

# ── 1. Load data ──────────────────────────────────────────────────────────
dc = DataContainer.from_dataset("${cfg.dataset}")
df = dc.read_table("${cfg.dataset}")
print(f"Loaded {len(df):,} rows")

# ── 2. Prepare ────────────────────────────────────────────────────────────
TARGET = "${cfg.targetCol ?? 'target'}"
X = df.drop(columns=[TARGET])
y = df[TARGET]
X = pd.get_dummies(X, drop_first=True)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=${cfg.testSplit ?? 0.2}, random_state=42,
    stratify=y if "${cfg.taskType}" == "classification" else None
)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# ── 3. Train ──────────────────────────────────────────────────────────────
${trainBlock}

# ── 4. Evaluate ───────────────────────────────────────────────────────────
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
executor.log_metrics({"accuracy": acc, "dataset": "${cfg.dataset}"})
print(f"Accuracy: {acc:.4f}")
print(classification_report(y_test, y_pred))

# ── 5. Save ───────────────────────────────────────────────────────────────
save_artifact(model, name="${cfg.name}", container="${cfg.dataset}")
print("Model artifact saved.")
`;
  }

  private slmFinetuneTraining(cfg: TrainingJobCfg): string {
    const method = cfg.method ?? 'LoRA';
    const is4bit = method === 'QLoRA' || cfg.quantization === '4-bit';
    const loadBlock = is4bit
      ? `bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, quantization_config=bnb_config, device_map="auto"
)`
      : `model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID, torch_dtype=torch.bfloat16, device_map="auto"
)`;
    return `"""
Auto-generated — SLM Fine-tuning (${method})
Job:       ${cfg.name}
Base Model: ${cfg.baseModel}
Method:    ${method}
Dataset:   ${cfg.dataset}
Executor:  ${cfg.executor}
"""

import torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, TaskType
from trl import SFTTrainer, SFTConfig
from essedum.data import DataContainer
from essedum.pipeline import save_artifact

MODEL_ID    = "${cfg.baseModel}"
JOB_NAME    = "${cfg.name}"
DATASET     = "${cfg.dataset}"
LORA_RANK   = ${cfg.loraRank ?? 16}
LORA_ALPHA  = ${cfg.loraAlpha ?? 32}
MAX_LEN     = ${cfg.maxLen ?? 2048}

# ── 1. Load tokenizer ─────────────────────────────────────────────────────
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# ── 2. Load model (${is4bit ? '4-bit quantized' : 'bf16'}) ──────────────────────────
${loadBlock}
model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})
model.enable_input_require_grads()

# ── 3. LoRA config ────────────────────────────────────────────────────────
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=LORA_RANK, lora_alpha=LORA_ALPHA, lora_dropout=0.05,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj",
                    "gate_proj", "up_proj", "down_proj"],
    bias="none",
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# ── 4. Dataset ────────────────────────────────────────────────────────────
dc = DataContainer.from_dataset(DATASET)
raw = dc.read_table(DATASET)

def format_sample(sample):
    return tokenizer.apply_chat_template(
        [{"role": "user",      "content": sample["instruction"]},
         {"role": "assistant", "content": sample["response"]}],
        tokenize=False, add_generation_prompt=False
    )

train_ds = Dataset.from_pandas(raw).map(lambda x: {"text": format_sample(x)})

# ── 5. Train ──────────────────────────────────────────────────────────────
training_args = SFTConfig(
    output_dir=f"./outputs/{JOB_NAME}",
    num_train_epochs=${cfg.epochs ?? 3},
    per_device_train_batch_size=${cfg.batchSize ?? 4},
    gradient_accumulation_steps=4,
    learning_rate=${cfg.lr ?? '2e-4'},
    lr_scheduler_type="cosine",
    warmup_ratio=0.05,
    bf16=True,
    logging_steps=10,
    save_strategy="epoch",
    max_seq_length=MAX_LEN,
)
trainer = SFTTrainer(
    model=model, args=training_args,
    train_dataset=train_ds, dataset_text_field="text",
    peft_config=lora_config,
)
trainer.train()

# ── 6. Save ───────────────────────────────────────────────────────────────
trainer.save_model(f"./outputs/{JOB_NAME}/final")
save_artifact(model, name=JOB_NAME, container=DATASET)
print(f"✓ Fine-tuned model saved: {JOB_NAME}")
`;
  }

  private reasoningTraining(cfg: TrainingJobCfg): string {
    const method = cfg.method ?? 'GRPO';
    const trlImport = method === 'DPO' ? 'DPOTrainer, DPOConfig' : method === 'ORPO' ? 'ORPOTrainer, ORPOConfig' : 'GRPOTrainer, GRPOConfig';
    const trainerBlock = method === 'GRPO'
      ? `# ── 4. Reward functions ──────────────────────────────────────────────────
def accuracy_reward(completions, solution, **kw):
    rewards = []
    for c in completions:
        ans = re.search(r"<answer>(.*?)</answer>", c, re.DOTALL)
        rewards.append(1.0 if ans and ans.group(1).strip() == str(solution).strip() else 0.0)
    return rewards

def format_reward(completions, **kw):
    pattern = r"<think>.*?</think>\\s*<answer>.*?</answer>"
    return [0.5 if re.match(pattern, c, re.DOTALL) else 0.0 for c in completions]

# ── 5. GRPO Trainer ────────────────────────────────────────────────────────
config = GRPOConfig(
    output_dir=f"./outputs/{JOB_NAME}",
    num_train_epochs=${cfg.epochs ?? 3},
    per_device_train_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=${cfg.lr ?? '1e-5'},
    num_generations=8,
    max_prompt_length=512, max_completion_length=1024,
    kl_coeff=0.01, bf16=True,
)
trainer = GRPOTrainer(
    model=model, config=config, peft_config=lora_config,
    reward_funcs=[accuracy_reward, format_reward],
    train_dataset=Dataset.from_pandas(data),
)`
      : method === 'DPO'
      ? `# ── 4. DPO Trainer ───────────────────────────────────────────────────────
import copy
ref_model = copy.deepcopy(model)

config = DPOConfig(
    output_dir=f"./outputs/{JOB_NAME}",
    beta=0.1,
    num_train_epochs=${cfg.epochs ?? 2},
    per_device_train_batch_size=2, learning_rate=${cfg.lr ?? '5e-7'}, bf16=True,
)
trainer = DPOTrainer(
    model=model, ref_model=ref_model, args=config,
    train_dataset=Dataset.from_pandas(data),
)`
      : `# ── 4. ORPO Trainer (no reference model) ─────────────────────────────────
config = ORPOConfig(
    output_dir=f"./outputs/{JOB_NAME}",
    lambda_=0.1, num_train_epochs=${cfg.epochs ?? 3},
    per_device_train_batch_size=2, learning_rate=${cfg.lr ?? '8e-6'}, bf16=True,
)
trainer = ORPOTrainer(model=model, args=config, peft_config=lora_config,
    train_dataset=Dataset.from_pandas(data))`;
    return `"""
Auto-generated — Reasoning Model Training (${method})
Job:        ${cfg.name}
Base Model: ${cfg.baseModel}
Dataset:    ${cfg.dataset}
Executor:   ${cfg.executor}
"""

import re, torch
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig
from trl import ${trlImport}
from essedum.data import DataContainer
from essedum.pipeline import save_artifact

MODEL_ID = "${cfg.baseModel}"
JOB_NAME = "${cfg.name}"

SYSTEM_PROMPT = """
You are a helpful reasoning assistant. Think step by step.
Use <think>...</think> for reasoning and <answer>...</answer> for your final answer.
"""

# ── 1. Load model ─────────────────────────────────────────────────────────
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, torch_dtype=torch.bfloat16, device_map="auto")
model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})

# ── 2. LoRA for efficient training ────────────────────────────────────────
lora_config = LoraConfig(r=${cfg.loraRank ?? 16}, lora_alpha=${cfg.loraAlpha ?? 32}, lora_dropout=0.05,
    target_modules=["q_proj","v_proj","k_proj","o_proj"], bias="none")

# ── 3. Dataset ────────────────────────────────────────────────────────────
dc   = DataContainer.from_dataset("${cfg.dataset}")
data = dc.read_table("${cfg.dataset}")

${trainerBlock}
trainer.train()

# ── 6. Save ───────────────────────────────────────────────────────────────
trainer.save_model(f"./outputs/{JOB_NAME}/final")
save_artifact(model, name=JOB_NAME, container="${cfg.dataset}")
print(f"✓ Reasoning model saved: {JOB_NAME}")
`;
  }

  private distillationTraining(cfg: TrainingJobCfg): string {
    return `"""
Auto-generated — Model Distillation
Job:     ${cfg.name}
Teacher: ${cfg.teacher ?? 'gpt-4o'}
Student: ${cfg.baseModel}
Method:  ${cfg.method ?? 'SFT-distill'}
Dataset: ${cfg.dataset}
"""

import json, torch
from tqdm import tqdm
from openai import AzureOpenAI
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from peft import LoraConfig
from trl import SFTTrainer, SFTConfig
from essedum.data import DataContainer
from essedum.pipeline import save_artifact

TEACHER_ID  = "${cfg.teacher ?? 'gpt-4o'}"
STUDENT_ID  = "${cfg.baseModel}"
JOB_NAME    = "${cfg.name}"

# ── 1. Load raw prompts ───────────────────────────────────────────────────
dc   = DataContainer.from_dataset("${cfg.dataset}")
data = dc.read_table("${cfg.dataset}")   # expects "prompt" column

# ── 2. Generate teacher outputs ───────────────────────────────────────────
client  = AzureOpenAI()
outputs = []

for _, row in tqdm(data.iterrows(), total=len(data), desc="Teacher inference"):
    resp = client.chat.completions.create(
        model=TEACHER_ID,
        messages=[{"role": "user", "content": row["prompt"]}],
        temperature=0.7, max_tokens=1024,
    )
    outputs.append({"prompt": row["prompt"], "response": resp.choices[0].message.content})

teacher_ds = Dataset.from_list(outputs)
print(f"Generated {len(teacher_ds):,} teacher samples")

# ── 3. Student SFT on teacher outputs (Sequence-KD) ──────────────────────
tokenizer = AutoTokenizer.from_pretrained(STUDENT_ID, use_fast=True)
tokenizer.pad_token = tokenizer.eos_token

student_model = AutoModelForCausalLM.from_pretrained(STUDENT_ID, torch_dtype=torch.bfloat16, device_map="auto")
lora_config   = LoraConfig(r=${cfg.loraRank ?? 16}, lora_alpha=${cfg.loraAlpha ?? 32}, lora_dropout=0.05,
    target_modules=["q_proj","v_proj","k_proj","o_proj"], bias="none")

def format_kd(sample):
    return tokenizer.apply_chat_template(
        [{"role": "user", "content": sample["prompt"]},
         {"role": "assistant", "content": sample["response"]}],
        tokenize=False, add_generation_prompt=False
    )

train_ds = teacher_ds.map(lambda x: {"text": format_kd(x)})

training_args = SFTConfig(
    output_dir=f"./outputs/{JOB_NAME}",
    num_train_epochs=${cfg.epochs ?? 3},
    per_device_train_batch_size=${cfg.batchSize ?? 4},
    gradient_accumulation_steps=4,
    learning_rate=${cfg.lr ?? '2e-4'},
    bf16=True, logging_steps=10, save_strategy="epoch",
    max_seq_length=${cfg.maxLen ?? 2048},
)
trainer = SFTTrainer(
    model=student_model, args=training_args,
    train_dataset=train_ds, dataset_text_field="text",
    peft_config=lora_config,
)
trainer.train()

# ── 4. Save ───────────────────────────────────────────────────────────────
trainer.save_model(f"./outputs/{JOB_NAME}/final")
save_artifact(student_model, name=JOB_NAME, container="${cfg.dataset}")
print(f"✓ Distilled student saved: {JOB_NAME}")
`;
  }
}
